version: '3.4'
services:
  basket.api:
   ports:
    - 5000:8080
  order.api:
   ports:
    - 5002:8080
  sqlserver.database:
   environment:
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=Password12*
    - MSSQL_PID=Evaluation
   ports:
    - 1433:1433